on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

name: Git Sync
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v2
      - name: Mirror Github to Gitee with white list
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/LoveGlaze
          dst: gitee/LoveGlaze
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          static_list:  ${{ github.event.repository.name }}
          force_update: true